### ISSUE TITLE
Test PyPI FASTSim name collision

### ISSUE THREAD

**Issue by kylecarow** [ojdf/fast#7]
Hello there,

I am one of the developers of NREL's FASTSim: https://pypi.org/project/fastsim/ https://github.com/NREL/fastsim/

In trying to set up Test PyPI for our package, we discovered that PyPI will not let us create a project named `fastsim`, likely due to this project's Test PyPI project: https://test.pypi.org/project/fast-sim/. I expect that you have already run into this issue on PyPI proper, given the altered project name: https://pypi.org/project/fast-aosim/

Would it be possible to work together to resolve this collision? Unfortunately I feel like the easiest way to resolve this is if you would be okay with removing the Test PyPI project `fast-sim`, then you could republish it to be consistent with PyPI, i.e. with the name `fast-aosim`.

I fully understand this may be an inconvenience to you and would appreciate your feedback.

**Comment by ojdf** [comment]
Hi @kylecarow 

You are absolutely correct in that due to collision with your project on PyPI I renamed from fast-sim to fast-aosim, I did not spot this beforehand. I have deleted my test.pypi version of fast-sim, as I don't really need it anyway. This is the problem when you name your project something as generic as "fast"! 

Cheers
Ollie

**Comment by kylecarow** [comment]
This resolved the name collision! Thanks for your help!
